---
# Array of 3D positions for detected bottles and cans
geometry_msgs/Point[] positions

# Corresponding array of pitch angles for detected bottles and cans
float32[] pitches

# Corresponding array of yaw angles for detected bottles and cans
float32[] yaws

# Corresponding array of the type of recyclable (0 = bottle; 1 = can)
uint8[] types

# Corresponding array of the maximum measured height of each object
float32[] heights
